[ELYEE-40] Upgrade version.org.glassfish.soteria from 3.0.0 to 3.0.3
wildfly-security/wildfly-elytron-ee pull request #27
Opened 2023-09-08 11:37 UTC by Skyllarr

https://issues.redhat.com/browse/ELYEE-40

2023-09-08 12:24 UTC, Skyllarr commented
@fjuma please review

2023-09-08 15:45 UTC, fjuma approved these changes
Thanks @Skyllarr!

2024-04-09 15:30 UTC, darranl requested changes
When updating the Soteria version we also need to check the classes forked from Soteria.

I am going to see if we can get a Soteria release that removes the need for the forked classes.

2025-02-19 19:15 UTC, darranl commented
Superseded by https://github.com/wildfly-security/wildfly-elytron-ee/pull/51

2025-02-19 19:15 UTC, closed without merging